#include "menus/menu.h"

#ifdef GCN_PLATFORM
#define ANY_SPECIALS_AMNT 21

enum AnyPracticeIndex {
    ORDON_GATE_CLIP_INDEX,
    BACK_IN_TIME_INDEX,
    GOATS_INDEX,
    HUGO_INDEX,
    EMS_INDEX,
    MIST_INDEX,
    FRST_BIT_INDEX,
    FRST_ESCAPE_INDEX,
    GORGE_VOID_INDEX,
    RUPEE_ROLL_INDEX,
    LANAYRU_GATE_CLIP_INDEX,
    KARG_INDEX,
    ELDIN_TWILIGHT_INDEX,
    BOMB_HOUSE_SKIP_INDEX,
    LANAYRU_TWILIGHT_INDEX,
    WATERFALL_SIDEHOP_INDEX,
    BOSS_BUG_INDEX,
    IZA_INDEX,
    PLUMM_OOB_INDEX,
    ELH_INDEX,
    LAKEBED_1_INDEX,
    TOAD_INDEX,
    LAKEBED_BK_SKIP_INDEX,
    ONEBOMB_INDEX,
    MDH_TOWER_INDEX,
    MDH_BRIDGE_INDEX,
    SPR_WARP_SKIP_INDEX,
    SPR_INDEX,
    DARK_HAMMER_INDEX,
    BULBLIN_CAMP_INDEX,
    AG_INDEX,
    POE_1_SKIP_INDEX,
    DSS_INDEX,
    STALLORD_INDEX,
    STALLORD2_INDEX,
    CITS_EARLY_INDEX,
    CITS_1_INDEX,
    AERALFOS_SKIP_INDEX,
    CITS_2_INDEX,
    FAN_TOWER_INDEX,
    ARGOROK_INDEX,
    PALACE_1_INDEX,
    PALACE_2_INDEX,
    EARLY_PLATFORM_INDEX,
    ZANT_INDEX,
    HC_INDEX,
    DARKNUT_INDEX,
    HC_TOWER_INDEX,
    BEAST_GANON_INDEX,
    HORSEBACK_GANON_INDEX,

    // Entry used as a count of entries
    ANY_SAVES_COUNT
};
#endif
#ifdef WII_PLATFORM
#define ANY_SPECIALS_AMNT 12
enum AnyPracticeIndex {
    ORDON_GATE_CLIP_INDEX,
    BACK_IN_TIME_INDEX,
    FARON_GATE_CLIP_1_INDEX,
    SEAM_CLIP_INDEX,
    OOB_TO_GORGE_INDEX,
    FARON_GATE_CLIP_2_INDEX,
    GOATS_INDEX,
    HUGO_INDEX,
    BITE_FARON_TWILIGHT_INDEX,
    EMS_INDEX,
    MIST_INDEX,
    BITE_INDEX,
    KB1_INDEX,
    ELDIN_TWILIGHT_INDEX,
    BOMBHOUSE_SKIP_INDEX,
    EPONA_OOB_INDEX,
    KARG_FIGHT_INDEX,
    KARG_FLIGHT_INDEX,
    LANAYRU_TWILIGHT_INDEX,
    WATERFALL_SIDEHOP_INDEX,
    BOSS_BUG_INDEX,
    IZA_INDEX,
    PLUMM_OOB_INDEX,
    ENTER_LAKEBED_INDEX,
    LAKEBED_1_INDEX,
    POT_PUSH_INDEX,
    TOAD_INDEX,
    LAKEBED_BK_SKIP_INDEX,
    MORPHEEL_INDEX,
    LOUISE_GLITCH_INDEX,
    ROPE_SKIP_INDEX,
    MDH_TOWER_INDEX,
    MDH_BRIDGE_INDEX,
    MESSENGER_SKIP_INDEX,
    SPR_MBBB_INDEX,
    SPR_FREEZARD_INDEX,
    DARK_HAMMER_INDEX,
    BULBLIN_CAMP_INDEX,
    AG_INDEX,
    POE_GATE_SKIP_INDEX,
    PGS_EBMB_INDEX,
    EARLY_BOSS_KEY_INDEX,
    TRIPLE_STALFOS_SKIP_INDEX,
    DSS_INDEX,
    EPIC_SPINNER_INDEX,
    STALLORD_INDEX,
    STALLORD_2_INDEX,
    CITS_EARLY_INDEX,
    CITS_1_INDEX,
    ARG_CS_SKIP_INDEX,
    CITS_WEST_INDEX,
    AERALFOS_SKIP_INDEX,
    CITS_2_INDEX,
    CITS_BK_CLIP_INDEX,
    CITS_FANLESS_INDEX,
    FAN_TOWER_INDEX,
    ARGOROK_INDEX,
    PALACE_SOL_1_INDEX,
    PALACE_SOL_2_INDEX,
    PALACE_2_INDEX,
    PALACE_BK_INDEX,
    EARLY_PLATFORM_INDEX,
    ZANT_INDEX,
    ZANT_DANGORO_INDEX,
    ZANT_FINAL_INDEX,
    HC_INDEX,
    KB4_INDEX,
    DARKNUT_INDEX,
    HC_AERALFOS_INDEX,
    HC_TOWER_INDEX,
    BEAST_GANON_INDEX,
    HORSEBACK_GANON_INDEX,

    // Entry used as a count of entries
    ANY_SAVES_COUNT
};
#endif

class AnySavesMenu : public Menu {
public:
    AnySavesMenu(Cursor& cursor);
    virtual ~AnySavesMenu();
    virtual void draw();

private:
#ifdef GCN_PLATFORM
    Line lines[ANY_SAVES_COUNT];
#endif
#ifdef WII_PLATFORM
    Line lines[ANY_SAVES_COUNT];
#endif
};